### ISSUE TITLE
Website Doesn't Load Content Without JavaScript

### ISSUE THREAD

**Issue by ben9583** [shrays/Personal-Website#11]
I've noticed an issue when visiting the website. Specifically, when I try to access resources (for instance, loading the homepage), there is no content that appears and I instead get a message saying "You need to enable JavaScript to run this app."

<img width="1792" alt="You need to enable JavaScript to run this app." src="https://github.com/shrays/Personal-Website/assets/16968917/e30f42db-6b8b-4769-a9e3-76529396f17b">

I'm currently unable to use the website because of this issue.

Steps to Reproduce:

1. Open a browser (I've found this occurs on any of them)
2. Disable JavaScript
3. Visit https://shrayswarup.com

*Was this helpful? [Click here (Shray only)](https://raspi.ben9583.com/feedback?code=0HYY7maHcE5ahyJ6KRnS9NhVZItOCDmw) to leave feedback. Not working? Visit https://raspi.ben9583.com/feedback and use the code "0HYY7maHcE5ahyJ6KRnS9NhVZItOCDmw" (no quotes, Shray only, please).*

**Comment by shrays** [comment]
Since this project is a react-based web application, the website does not function with JavaScript disabled. Currently there are no immediate plans to fix this.
