### ISSUE TITLE
Error: "Could not find light with id: d073d569b62a"

### ISSUE THREAD

**Issue by ben9583** [shrays/Personal-Website#12]
Hi,

When visiting this website, I'm getting an error checking the status of the light. Specifically, the request to the `/status` and `/toggle` endpoints return the following message:

```json
{"error":"Could not find light with id: d073d569b62a"}
```

This is different from the expected behavior of returning whether the light is on and toggling the status, respectively. Furthermore, even though the response body clearly indicates an error, the endpoints still return HTTP status code `200`, indicating that the request was successful.

*Was this helpful? [Click here (Shray only)](https://raspi.ben9583.com/feedback?code=WhBcWKax2ft9biUQtpmA3ITKkcShavcF) to leave feedback. Not working? Visit https://raspi.ben9583.com/feedback and use the code "WhBcWKax2ft9biUQtpmA3ITKkcShavcF" (no quotes, Shray only, please).*

**Comment by shrays** [comment]
Hello,
This error occurred because the light had been moved and reset to factory settings. It is now online and and a more accurate status code will be displayed after the development branch is published.
